### ISSUE TITLE
qq音乐和咪咕音乐无法使用

### ISSUE THREAD

**Issue by IsaacWangTT** [pcrbot/music#11]
搜索时一直显示"什么也没有找到的说OxO"，应该是接口出了问题

**Comment by IsaacWangTT** [comment]
咪咕的时灵时不灵，但是qq音乐的接口绝对掉了

**Comment by laipz8200** [comment]
QQ Music 已在 a0d6b9cced2ae79899b28d40dff1d9095dfe23c8 中更新，咪咕等确认失效后再更新
