### ISSUE TITLE
机器人返回的歌单，希望加上音源网站的区分

### ISSUE THREAD

**Issue by shadow7755** [pcrbot/music#2]
比如改成下面这样，因为是从2个网站的库里搜索的，希望能区分下来源，因为我发现一些海外的群员有的网易听不了，只能听QQ的，可能是版权的问题？希望能在返回的歌单标记一下区分。

我找到了这些~!
网易云 0. Sonic Advance - Secret Base Zone - Goodknight Productions
网易云 1. secret base ~君がくれたもの~ - ZONE
网易云 2. secret base ~君がくれたもの~ - ZONE
QQ 3. Secret Base - ZONE
QQ 4. secret base (原唱: ZONE) - 麦小兜
QQ 5. Secret Base (原唱:ZONE) - 冥羽歆 坏叔
发送[选择]+序号来听歌吧~

**Comment by laipz8200** [comment]
已添加
